#!/bin/bash

# Setup directories
if [[ ! -d $PWD/config/certificates ]]; then
    mkdir -p $PWD/config/certificates
    echo "Created "$PWD"/config/certificates"
fi

if [[ ! -d $PWD/config/hosts ]]; then
    mkdir -p $PWD/config/hosts
    echo "Created "$PWD"/config/hosts"
fi

if [[ ! -d $PWD/data/databases ]]; then
    mkdir -p $PWD/data/databases
    echo "Created "$PWD"/data/databases"
fi

if [[ ! -d $PWD/data/editors/code-server ]]; then
    mkdir -p $PWD/data/editors/code-server
    echo "Created "$PWD"/data/editors/code-server"
fi

if [[ ! -d $PWD/data/editors/vscode-server ]]; then
    mkdir -p $PWD/data/editors/vscode-server
    echo "Created "$PWD"/data/editors/vscode-server"
fi

if [[ ! -d $PWD/data/editors/vscode-server-host ]]; then
    mkdir -p $PWD/data/editors/vscode-server-host
    echo "Created "$PWD"/data/editors/vscode-server-host"
fi

if [[ ! -d $PWD/data/www ]]; then
    mkdir -p $PWD/data/www
    echo "Created "$PWD"/data/www"
fi


# Create .env file
if [[ ! -f $PWD/.env ]]; then
    cp $PWD/.env-example $PWD/.env
    echo "Created .env file - please set your own values here"
    nano $PWD/.env
fi


# Ensure git credentials
if [[ -z $(git config --global user.name) ]]; then
    source $PWD/.env
    echo "Setting git credentials: $GIT_NAME / $GIT_EMAIL"
    git config --global user.name $GIT_NAME
    git config --global user.email $GIT_EMAIL
fi
