version: "3.5"
services:
    # ------------------------------------------------------------
    # PHP
    # ------------------------------------------------------------
    php:
        build:
            context: services/php
            args:
                - USERNAME
                - PASSWORD
        container_name: php
        hostname: nucleus
        restart: always
        working_dir: /srv/www/sites/
        ports:
            - "2222:22"
        env_file:
            - ../../.env
        environment:
            - GIT_NAME
            - GIT_EMAIL
            - USERNAME
            - PASSWORD
        depends_on:
            - memcached
        networks:
            nucleus:
                ipv4_address: 172.16.230.20
        volumes:
            - util:/srv/util/:rw
            - ../../:/srv/nucleus/:rw
            - ./services/php/config/ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:ro
            - ./services/php/config/fpm-overrides.conf:/etc/php/7.3/fpm/pool.d/zz-overrides.conf:ro
            - /etc/ssh/:/etc/ssh/:ro
            - ../../config/ssh/:/home/${USERNAME}/.ssh/
            - ../../data/editors/vscode-server/:/home/${USERNAME}/.vscode-server/
            - ${NUCLEUS_WWW}:/srv/www/

    # ------------------------------------------------------------
    # nginx
    # ------------------------------------------------------------
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx.nucleus
        restart: always
        working_dir: /srv/www/sites/
        ports:
            - "127.0.0.1:${HTTP_PORT}:80"
            - "127.0.0.1:${HTTPS_PORT}:443"
        depends_on:
            - php
        networks:
            nucleus:
                ipv4_address: 172.16.230.21
        volumes:
            - util:/srv/util/:rw
            - ../../:/srv/nucleus/:ro
            - ./services/nginx/snippets/:/etc/nginx/snippets/:ro
            - ./services/nginx/hosts/:/etc/nginx/conf.d/:ro
            - ${NUCLEUS_WWW}:/srv/www/

    # ------------------------------------------------------------
    # Maria Database
    # ------------------------------------------------------------
    mariadb:
        image: mariadb:10.4
        container_name: mariadb
        hostname: mariadb.nucleus
        restart: always
        working_dir: /srv/db
        environment:
            - MYSQL_ROOT_PASSWORD=${PASSWORD}
            - MYSQL_USER=${USERNAME}
            - MYSQL_PASSWORD=${PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "127.0.0.1:3306:3306"
        networks:
            nucleus:
                ipv4_address: 172.16.230.22
        volumes:
            - mariadb:/var/lib/mysql/:rw
            - ./services/mariadb/config/overrides.cnf:/etc/mysql/conf.d/overrides.cnf:ro
            - ./services/mariadb/data/pma-tables.sql:/docker-entrypoint-initdb.d/pma-tables.sql:ro
            - ./services/mariadb/data/pma-user.sql:/docker-entrypoint-initdb.d/pma-user.sql:ro

    # ------------------------------------------------------------
    # Memcache
    # ------------------------------------------------------------
    memcached:
        image: memcached
        container_name: memcached
        hostname: memcached.nucleus
        restart: always
        networks:
            nucleus:
                ipv4_address: 172.16.230.23

    # ------------------------------------------------------------
    # Redis
    # ------------------------------------------------------------
    redis:
        image: redis
        container_name: redis
        hostname: redis.nucleus
        restart: always
        networks:
            nucleus:
                ipv4_address: 172.16.230.24

    # ------------------------------------------------------------
    # Ungit
    # ------------------------------------------------------------
    ungit:
        build:
            context: services/ungit
            args:
                - USERNAME
                - PASSWORD
        container_name: ungit
        hostname: ungit.nucleus
        restart: always
        env_file:
            - ../../.env
        environment:
            - GIT_NAME
            - GIT_EMAIL
            - USERNAME
            - PASSWORD
        working_dir: /srv/www/sites/
        networks:
            nucleus:
                ipv4_address: 172.16.230.25
        volumes:
            - ../../config/ssh/:/home/${USERNAME}/.ssh/
            - ${NUCLEUS_WWW}:/srv/www/

# ------------------------------------------------------------
# Networks
# ------------------------------------------------------------
networks:
    nucleus:
        name: nucleus
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.16.230.0/24

# ------------------------------------------------------------
# Volumes
# ------------------------------------------------------------
volumes:
    util:
    mariadb:
