version: "3.1"
services:
    # ------------------------------------------------------------
    # PHP
    # ------------------------------------------------------------
    php:
        build: services/php
        container_name: php
        hostname: php
        restart: always
        working_dir: /srv/www/sites/
        ports:
            - "2222:22"
        env_file:
            - ../../.env
        environment:
            - GIT_NAME
            - GIT_EMAIL
            - PASSWORD
        depends_on:
            - memcached
        volumes:
            - util:/srv/util/:rw
            - ../../:/srv/nucleus/:rw
            - ./services/php/config/ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:ro
            - ./services/php/config/fpm-overrides.conf:/etc/php/7.3/fpm/pool.d/zz-overrides.conf:ro
            - ../../config/ssh/:/home/nucleus/.ssh/
            - ../../data/editors/vscode-server/:/home/nucleus/.vscode-server/
            - ${NUCLEUS_WWW}:/srv/www/

    # ------------------------------------------------------------
    # nginx
    # ------------------------------------------------------------
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx
        restart: always
        working_dir: /srv/www/sites/
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        depends_on:
            - php
        volumes:
            - util:/srv/util/:rw
            - ../../:/srv/nucleus/:ro
            - ./services/nginx/snippets/:/etc/nginx/snippets/:ro
            - ./services/nginx/hosts/:/etc/nginx/conf.d/:ro
            - ${NUCLEUS_WWW}:/srv/www/

    # ------------------------------------------------------------
    # Maria Database
    # ------------------------------------------------------------
    mariadb:
        image: mariadb:10.4
        container_name: mariadb
        hostname: mariadb
        restart: always
        working_dir: /srv/db
        environment:
            - MYSQL_ROOT_PASSWORD=${PASSWORD}
            - MYSQL_USER=${USERNAME}
            - MYSQL_PASSWORD=${PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - mariadb:/var/lib/mysql/:rw
            - ./services/mariadb/config/overrides.cnf:/etc/mysql/conf.d/overrides.cnf:ro
            - ./services/mariadb/data/pma-tables.sql:/docker-entrypoint-initdb.d/pma-tables.sql:ro
            - ./services/mariadb/data/pma-user.sql:/docker-entrypoint-initdb.d/pma-user.sql:ro

    # ------------------------------------------------------------
    # Memcache
    # ------------------------------------------------------------
    memcached:
        image: memcached
        container_name: memcached
        restart: always

    # ------------------------------------------------------------
    # Redis
    # ------------------------------------------------------------
    redis:
        image: redis
        container_name: redis
        restart: always

# ------------------------------------------------------------
# Volumes
# ------------------------------------------------------------
volumes:
    util:
    mariadb:
