version: "3.1"
services:
    # ------------------------------------------------------------
    # Code server
    # ------------------------------------------------------------
    code-server:
        build: services/code-server
        container_name: code-server
        restart: always
        network_mode: host
        environment:
            - GIT_NAME
            - GIT_EMAIL
            - PASSWORD
        ports:
            - "8080:8080"
        volumes:
            - ../../config/ssh/:/home/coder/.ssh/
            - ../../data/editors/code-server/:/home/coder/.local/share/code-server
            - ../../:/srv/nucleus
            - ${NUCLEUS_WWW}:/srv/www
    # ------------------------------------------------------------
    # Theia
    # ------------------------------------------------------------
    #theia:
    #  image: theiaide/theia:next
    #  container_name: theia
    #  restart: always
    #  ports:
    #    - "3000:3000"
    #  volumes:
    #    - ../../data/editors/theia/settings/:/home/theia/.theia
    #    - ${NUCLEUS_WWW}:/home/project
