version: "3.5"
services:
    # ------------------------------------------------------------
    # Code server
    # ------------------------------------------------------------
    code-server:
        build: services/code-server
        container_name: code-server
        hostname: code.nucleus
        restart: always
        network_mode: host
        environment:
            - GIT_NAME
            - GIT_EMAIL
            - USERNAME
            - PASSWORD
        ports:
            - "8080:8080"
        volumes:
            - ../../config/ssh/:/home/coder/.ssh/
            - ../../data/editors/code-server/:/home/coder/.local/share/code-server
            - ../../:/srv/nucleus
            - ${NUCLEUS_WWW}:/srv/www/
