#!/bin/bash

STACK=${1:=www}

case $STACK in
    www)
        SERVICE=php
        ;;

    code)
        SERVICE=code-server
        ;;
esac

if [ -z `docker-compose -f $PWD/stacks/$STACK/docker-compose.yml ps -q $SERVICE` ] || [ -z `docker ps -q --no-trunc | grep $(docker-compose -f $PWD/stacks/$STACK/docker-compose.yml ps -q $SERVICE)` ]; then
    docker-compose -f $PWD/stacks/$STACK/docker-compose.yml up -d
fi
