#!/bin/bash

DETAILS="/C=GB/ST=London/L=London/O=nucleus/OU=dev/CN=nucleus"
EXTFILE=$PWD/stacks/www/services/php/config/nucleus.localtest.ext

if [[ ! -d $PWD/config/certificates/ ]]; then
    mkdir -p $PWD/config/certificates/
fi

if [[ ! -f $PWD/config/certificates/nucleus.bundle.crt ]]; then
    LAST=$PWD
	cd $PWD/config/certificates/
	openssl genrsa -des3 -passout pass:nucleus -out nucleus.ca.key 2048
	openssl req -x509 -new -nodes -passin pass:nucleus -key nucleus.ca.key -sha256 -days 1825 -out nucleus.ca.pem -subj $DETAILS
	openssl dhparam -out dhparams.pem 2048
	openssl genrsa -passout pass:nucleus -out nucleus.localtest.key 2048
	openssl req -new -passin pass:nucleus -key nucleus.localtest.key -out nucleus.localtest.csr -subj $DETAILS
	openssl x509 -req -in nucleus.localtest.csr -CA nucleus.ca.pem -CAkey nucleus.ca.key -CAcreateserial -passin pass:nucleus -out nucleus.localtest.crt -days 1825 -sha256 -extfile $EXTFILE
	cat nucleus.localtest.crt nucleus.ca.pem > nucleus.bundle.crt
    cd $LAST
fi
